server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  datasource:
    url: jdbc:mysql://oauth.c1fwnmiscxdz.ap-northeast-2.rds.amazonaws.com:3306/oauth
    username: segeg
    password: dlwnsgk2!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#  security:
#    user:
#      name: admin
#      password: admin
#    oauth2:
#      client:
#        registration:
#          github: 
#            client-id: 2405598203009002
#            client-secret: 1f3fc0329a646a9b162d7b58a9f64067
##            redirect-uri: http://localhost/facebook/oauth/redirect
#            redirect-uri-template: http://localhost/facebook/oauth/redirect
#            scope:
#            - email
#            - public_profile